directories:
  output: release
  buildResources: build
appId: com.lifeville.quiz-app
productName: Lifeville Quiz App
files:
  - filter:
      - dist/
      - out/
      - node_modules/
      - package.json
      - '!node_modules/.cache'
      - '!**/.{git,svn,hg,DS_Store}'
      - '!**/._*'
      - '!**/{__tests__,test,tests,testing}/**'
      - '!**/*.{spec,test}.{js,ts,jsx,tsx}'
      - '!**/{.eslintrc,.eslintrc.js,.eslintrc.json}'
      - '!**/tsconfig*.json'
      - '!**/.{nyc_output,coverage,COVERAGE,lcov-report}'
extraResources:
  - from: data/
    to: data/
    filter:
      - '**/*'
nodeGypRebuild: false
buildDependenciesFromSource: false
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
        - ia32
  requestedExecutionLevel: asInvoker
  artifactName: ${productName}-${version}-${os}-${arch}.${ext}
  verifyUpdateCodeSignature: false
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Lifeville Quiz App
  include: build/installer.nsh
  displayLanguageSelector: true
  multiLanguageInstaller: true
  packElevateHelper: true
  allowElevation: true
  runAfterFinish: true
  menuCategory: Education
portable:
  artifactName: ${productName}-${version}-${os}-${arch}-portable.${ext}
compression: normal
publish: null
electronVersion: 22.3.27
